/**
 * WellView's unit conversions — GENERATED, do not edit by hand.
 *
 * Source: WellView_files/system/Peloton.Common.Units, the Access database the
 * desktop itself converts with; regenerate with
 * `node scripts/wellview-db/build_units.mjs`.
 *
 * Each row says how one USER unit relates to its BASE unit:
 *
 *     base = ((user - offset) * factor) ^ exponent
 *
 * A unit name determines its base uniquely — no name appears under two bases —
 * which is what makes refusing a cross-family conversion automatic rather than
 * a rule someone has to maintain.
 *
 * Two rows are CORRECTED against the shipped file, each because it contradicts
 * Peloton's own other rows; `corrected` carries the reason and `shippedFactor`
 * the value that was replaced.
 */
export interface UnitRow {
  /** The unit the database stores. */
  base: string;
  /** The unit a user sees. */
  unit: string;
  /** Peloton's own description. */
  label: string;
  factor: number;
  exponent: number;
  offset: number;
  /** Set when this app overrode the shipped factor, with the reason. */
  corrected?: string;
  shippedFactor?: number;
  /** Set when the relationship is not a plain scale. */
  note?: string;
}

export const UNIT_ROWS: readonly UnitRow[] = [
  {"base":"Proportion","unit":"%","label":"Percent","factor":0.01,"exponent":1,"offset":0},
  {"base":"m³/m³","unit":"% v/v","label":"Percent by volume","factor":0.01,"exponent":1,"offset":0},
  {"base":"°","unit":"°","label":"Degrees of angle","factor":1,"exponent":1,"offset":0},
  {"base":"°/m","unit":"°/100ft","label":"Degrees of angle per hundred feet","factor":0.0328083989501312,"exponent":1,"offset":0},
  {"base":"°/m","unit":"°/10m","label":"Degrees of angle per ten meters","factor":0.1,"exponent":1,"offset":0},
  {"base":"°/m","unit":"°/30m","label":"Degrees of angle per thirty meters","factor":0.0333333333333333,"exponent":1,"offset":0},
  {"base":"°/m","unit":"°/m","label":"Degrees of angle per meter","factor":1,"exponent":1,"offset":0},
  {"base":"kg/m³","unit":"°API","label":"API gravity","factor":0.00000706713780918728,"exponent":-1,"offset":-131.5,"note":"reciprocal with an offset: API = 141.5/SG − 131.5"},
  {"base":"°C","unit":"°C","label":"Degrees Celcius","factor":1,"exponent":1,"offset":0},
  {"base":"°C/m","unit":"°C/100m","label":"Degrees Celcius per hundred meters","factor":0.01,"exponent":1,"offset":0},
  {"base":"°C/m","unit":"°C/m","label":"Degrees Celcius per meter","factor":1,"exponent":1,"offset":0},
  {"base":"°C","unit":"°F","label":"Degrees Fahrenheit","factor":0.555555555555556,"exponent":1,"offset":32},
  {"base":"°C/m","unit":"°F/100ft","label":"Degrees Fahrenheit per hundred meters","factor":0.01822689,"exponent":1,"offset":0},
  {"base":"m","unit":"µm","label":"Microns","factor":0.000001,"exponent":1,"offset":0},
  {"base":"m²","unit":"µm²","label":"Square microns","factor":1e-12,"exponent":1,"offset":0},
  {"base":"S/m","unit":"µS/ft","label":"Microsiemens per foot","factor":0.00000328083989501312,"exponent":1,"offset":0},
  {"base":"S/m","unit":"µS/m","label":"Microsiemens per meter","factor":0.000001,"exponent":1,"offset":0},
  {"base":"m","unit":"1/32\"","label":"Thirty seconds of an inch","factor":0.00079375,"exponent":1,"offset":0},
  {"base":"m","unit":"1/64\"","label":"Sixty fourth of an inch","factor":0.000396875,"exponent":1,"offset":0},
  {"base":"1/m²","unit":"1/dm²","label":"Per decimeter","factor":100,"exponent":1,"offset":0},
  {"base":"1/m","unit":"1/ft","label":"Per foot","factor":3.28083989501312,"exponent":1,"offset":0},
  {"base":"1/m²","unit":"1/ft²","label":"Per square foot","factor":10.7639104167097,"exponent":1,"offset":0},
  {"base":"1/m","unit":"1/m","label":"Per meter","factor":1,"exponent":1,"offset":0},
  {"base":"1/unit","unit":"1/unit","label":"Per unit","factor":1,"exponent":1,"offset":0},
  {"base":"N•m","unit":"1000in•lb","label":"Thousand inch pounds(force)","factor":112.984829027617,"exponent":1,"offset":0},
  {"base":"kg","unit":"1000kg","label":"Thousand kilograms","factor":1000,"exponent":1,"offset":0},
  {"base":"N","unit":"1000lbf","label":"Thousand pounds force","factor":4448.2216152605,"exponent":1,"offset":0},
  {"base":"Cost","unit":"100k","label":"One hundred thousand cost units","factor":100000,"exponent":1,"offset":0},
  {"base":"N","unit":"100lbf","label":"One hundred pounds force","factor":444.82216152605,"exponent":1,"offset":0},
  {"base":"Cost","unit":"10k","label":"Ten thousand cost units","factor":10000,"exponent":1,"offset":0},
  {"base":"Cost","unit":"1k","label":"One thousand cost units","factor":1000,"exponent":1,"offset":0},
  {"base":"Cost","unit":"1M","label":"One million cost units","factor":1000000,"exponent":1,"offset":0},
  {"base":"A","unit":"A","label":"Amp","factor":1,"exponent":1,"offset":0},
  {"base":"m²","unit":"Acre","label":"US Survey Acre","factor":4046.87260987,"exponent":1,"offset":0},
  {"base":"kPa","unit":"atm","label":"Atmospheres","factor":101.325,"exponent":1,"offset":0},
  {"base":"kPa/m","unit":"bar/m","label":"Bars per m","factor":100,"exponent":1,"offset":0},
  {"base":"kPa","unit":"bars","label":"Bars","factor":100,"exponent":1,"offset":0},
  {"base":"m³","unit":"bbl","label":"Oil barrel","factor":0.158987294928,"exponent":1,"offset":0},
  {"base":"m³/rpm","unit":"bbl/100rpm","label":"Oil barrel per hundred rotations per minute","factor":0.00158987294928,"exponent":1,"offset":0},
  {"base":"m³/m²","unit":"bbl/acre","label":"Oil barrel per acre","factor":0.0000392869224639069,"exponent":1,"offset":0},
  {"base":"m³/m³","unit":"bbl/bbl","label":"Oil barrel per oil barrel","factor":1,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"bbl/day","label":"Oil barrel per day","factor":0.1589873,"exponent":1,"offset":0},
  {"base":"m³/day/kPa","unit":"bbl/day/psi","label":"Oil barrels per day per psi","factor":0.0230591575847658,"exponent":1,"offset":0},
  {"base":"m³/m","unit":"bbl/ft","label":"Oil barrel per foot","factor":0.52161187664042,"exponent":1,"offset":0},
  {"base":"m³/m³","unit":"bbl/ft³","label":"Oil barrels per cubic foot","factor":5.61458333333333,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"bbl/hr","label":"Oil barrel per hour","factor":3.8156952,"exponent":1,"offset":0},
  {"base":"m³/m","unit":"bbl/in","label":"Oil barrel per inch","factor":6.25934251968504,"exponent":1,"offset":0},
  {"base":"m³/m","unit":"bbl/m","label":"Oil barrel per meter","factor":0.1589873,"exponent":1,"offset":0},
  {"base":"m³/m³","unit":"bbl/MCF","label":"Oil barrels per thousand cubic feet","factor":0.00561458333333333,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"bbl/min","label":"Oil barrel per minute","factor":228.941712,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"bbl/s","label":"Oil barrel per second","factor":13736.50272,"exponent":1,"offset":0},
  {"base":"m³/stk","unit":"bbl/stk","label":"Oil barrel per stroke","factor":0.158987294928,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"bbl/yr","label":"Oil barrel per year","factor":0.00043558164,"exponent":1,"offset":0},
  {"base":"m³","unit":"BCF","label":"Billion cubic feet","factor":28316846.592,"exponent":1,"offset":0},
  {"base":"J","unit":"BTU","label":"British thermal units","factor":1055.05585262,"exponent":1,"offset":0},
  {"base":"J/m³","unit":"BTU/ft³","label":"British thermal units per cubic foot","factor":37258.9458078313,"exponent":1,"offset":0},
  {"base":"J/W/day","unit":"BTU/hp/hr","label":"British thermal units per horsepower hours","factor":33.9564769103012,"exponent":1,"offset":0},
  {"base":"byte","unit":"byte","label":"byte","factor":1,"exponent":1,"offset":0},
  {"base":"m³","unit":"cc","label":"Cubic centimeters","factor":0.000001,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"cc/30min","label":"Cubic centimeters per thirty minutes","factor":0.000048,"exponent":1,"offset":0},
  {"base":"m","unit":"cm","label":"Centimeter","factor":0.01,"exponent":1,"offset":0},
  {"base":"m²","unit":"cm²","label":"Square centimeter","factor":0.0001,"exponent":1,"offset":0},
  {"base":"m³","unit":"cm³","label":"Cubic centimeter","factor":0.000001,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"cm³/day","label":"Cubic centimeter per day","factor":0.000001,"exponent":1,"offset":0},
  {"base":"Cost","unit":"Cost","label":"Cost","factor":1,"exponent":1,"offset":0},
  {"base":"Cost/day","unit":"Cost/day","label":"Cost/day","factor":1,"exponent":1,"offset":0},
  {"base":"Cost/m","unit":"Cost/ft","label":"Cost/foot","factor":3.28083989501312,"exponent":1,"offset":0},
  {"base":"Cost/day","unit":"Cost/hr","label":"Cost/hour","factor":24,"exponent":1,"offset":0},
  {"base":"Cost/m","unit":"Cost/m","label":"Cost per meter","factor":1,"exponent":1,"offset":0},
  {"base":"Cost/unit","unit":"Cost/unit","label":"Cost/unit","factor":1,"exponent":1,"offset":0},
  {"base":"Pa•s","unit":"cp","label":"Centipoise","factor":0.001,"exponent":1,"offset":0},
  {"base":"N","unit":"daN","label":"Decanewton","factor":10,"exponent":1,"offset":0},
  {"base":"N/m","unit":"daN/mm","label":"Decanewton per millimeter","factor":10000,"exponent":1,"offset":0},
  {"base":"N•m","unit":"daN•m","label":"Decanewton meter","factor":10,"exponent":1,"offset":0},
  {"base":"m²","unit":"darcy","label":"Darcy","factor":9.869233e-13,"exponent":1,"offset":0},
  {"base":"days","unit":"days","label":"Days","factor":1,"exponent":1,"offset":0},
  {"base":"m","unit":"dm","label":"Decimeter","factor":0.1,"exponent":1,"offset":0},
  {"base":"m²","unit":"dm²","label":"Square decimeter","factor":0.010000000000000002,"exponent":1,"offset":0,"corrected":"shipped 100 is the RECIPROCAL, four orders of magnitude out: their own dm is 0.1 and their cm²/mm² are 0.01²/0.001², so a square decimetre is 0.01 m². 100 is exactly the factor on their 1/dm² row, which is correct there — copied into the wrong row","shippedFactor":100},
  {"base":"m³","unit":"dm³","label":"Cubic decimeter","factor":0.001,"exponent":1,"offset":0},
  {"base":"S/m","unit":"dS/ft","label":"Decisiemens per foot","factor":0.328083989501312,"exponent":1,"offset":0},
  {"base":"S/m","unit":"dS/m","label":"Decisiemens per meter","factor":10,"exponent":1,"offset":0},
  {"base":"kPa","unit":"dyne/cm²","label":"Dyne per square centimeter","factor":0.0001,"exponent":1,"offset":0},
  {"base":"m³","unit":"E3m³","label":"Thousand cubic meters","factor":1000,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"E3m³/day","label":"Thousand cubic meters per day","factor":1000,"exponent":1,"offset":0},
  {"base":"m³/m³","unit":"E3m³/m³","label":"Thousand cubic meters per meter","factor":1000,"exponent":1,"offset":0},
  {"base":"m³","unit":"E6m³","label":"Million cubic meters","factor":1000000,"exponent":1,"offset":0},
  {"base":"m³","unit":"E9m³","label":"Billion cubic meters","factor":1000000000,"exponent":1,"offset":0},
  {"base":"m","unit":"ft","label":"Feet","factor":0.3048,"exponent":1,"offset":0},
  {"base":"m","unit":"ft(elv)","label":"Feet - elevation, ie: increasing values going up","factor":-0.3048,"exponent":1,"offset":0},
  {"base":"m/day","unit":"ft/day","label":"Feet per day","factor":0.3048,"exponent":1,"offset":0},
  {"base":"m/day","unit":"ft/hr","label":"Feet per hour","factor":7.3152,"exponent":1,"offset":0},
  {"base":"m/day","unit":"ft/min","label":"Feet per minute","factor":438.912,"exponent":1,"offset":0},
  {"base":"m/day","unit":"ft/s","label":"Feet per second","factor":26334.72,"exponent":1,"offset":0},
  {"base":"N•m","unit":"ft•lb","label":"Foot pounds(force)","factor":1.3558179483314,"exponent":1,"offset":0},
  {"base":"m²","unit":"ft²","label":"Square foot","factor":0.09290304,"exponent":1,"offset":0,"corrected":"shipped 0.0929053 is neither 0.3048² (0.09290304, which their own ft and ft³ use) nor the US survey foot squared (0.09290341); a transposed digit","shippedFactor":0.0929053},
  {"base":"m³","unit":"ft³","label":"Cubic feet","factor":0.028316846592,"exponent":1,"offset":0},
  {"base":"m³/m³","unit":"ft³/bbl","label":"Cubic feet per barrel","factor":0.178107606679035,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"ft³/day","label":"Cubic feet per day","factor":0.028316846592,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"ft³/hr","label":"Cubic feet per hour","factor":0.679604318208,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"ft³/min","label":"Cubic feet per minute","factor":40.776264,"exponent":1,"offset":0},
  {"base":"m³/kg","unit":"ft³/sack","label":"Cubic feet per 100 pound sack","factor":0.000624279605761446,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"ft³/yr","label":"Cubic feet per year","factor":0.0000775804016219178,"exponent":1,"offset":0},
  {"base":"kg","unit":"g","label":"Grams","factor":0.001,"exponent":1,"offset":0},
  {"base":"kg/m³","unit":"g/cm³","label":"Grams per cubic centimeter","factor":1000,"exponent":1,"offset":0},
  {"base":"kg/kg","unit":"g/kg","label":"Grams per kilograms","factor":0.001,"exponent":1,"offset":0},
  {"base":"kg/m³","unit":"g/L","label":"Grams per liter","factor":1,"exponent":1,"offset":0},
  {"base":"ga","unit":"ga","label":"Gauge","factor":1,"exponent":1,"offset":0},
  {"base":"m³","unit":"gal","label":"US gallons","factor":0.003785411784,"exponent":1,"offset":0},
  {"base":"m³/m²","unit":"gal/acre","label":"US gallons per hectare","factor":9.35402717271866e-7,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"gal/day","label":"US gallons per day","factor":0.003785411784,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"gal/hr","label":"US gallons per hour","factor":0.0908496,"exponent":1,"offset":0},
  {"base":"m³/kg","unit":"gal/sack","label":"US gallons per 100 pound sack","factor":0.0000834540445201933,"exponent":1,"offset":0},
  {"base":"m³/stk","unit":"gal/stk","label":"US gallons per stroke","factor":0.003785411784,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"gal/yr","label":"US gallons per year","factor":0.00001037099,"exponent":1,"offset":0},
  {"base":"kPa","unit":"gf/100cm²","label":"Gram force per hundred square centimeters","factor":0.000981,"exponent":1,"offset":0},
  {"base":"J","unit":"GJ","label":"Gigajoule","factor":1000000000,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"gpm","label":"US Gallons per minute","factor":5.45099328,"exponent":1,"offset":0},
  {"base":"m²","unit":"ha","label":"Hectares","factor":10000,"exponent":1,"offset":0},
  {"base":"W","unit":"hp","label":"Horsepower","factor":745.6999,"exponent":1,"offset":0},
  {"base":"W/m²","unit":"hp/in²","label":"Horsepower per square inch","factor":1155837.15667431,"exponent":1,"offset":0},
  {"base":"days","unit":"hr","label":"Hours","factor":0.0416666666666667,"exponent":1,"offset":0},
  {"base":"Hz","unit":"Hz","label":"Hertz","factor":1,"exponent":1,"offset":0},
  {"base":"m","unit":"in","label":"Inches","factor":0.0254,"exponent":1,"offset":0},
  {"base":"m²","unit":"in²","label":"Square inches","factor":0.00064516,"exponent":1,"offset":0},
  {"base":"m²/day","unit":"in²/s","label":"Square inches per second","factor":55.741824,"exponent":1,"offset":0},
  {"base":"m³","unit":"in³","label":"Cubic inches","factor":0.000016387064,"exponent":1,"offset":0},
  {"base":"m³/m³","unit":"in³/in³","label":"Cubic inch per cubic inch","factor":1,"exponent":1,"offset":0},
  {"base":"kPa","unit":"inH2O","label":"Inches of water (4deg C)","factor":0.249082,"exponent":1,"offset":0},
  {"base":"J","unit":"J","label":"Joule","factor":1,"exponent":1,"offset":0},
  {"base":"J/m³","unit":"J/m³","label":"Joule per cubic meter","factor":1,"exponent":1,"offset":0},
  {"base":"°C","unit":"K","label":"Kelvin","factor":1,"exponent":1,"offset":273.15,"corrected":"shipped 273.1499938964844 is bit-exactly Math.fround(273.15) — a float32 that was widened into a double column, not a figure anyone chose. Their own °F row is exact, so this is a storage artefact of the same kind as the two above. It is worth 6.1e-6 K, far below any rig measurement; corrected for consistency rather than for consequence, and because a physical check whose tolerance is wide enough to miss it is not checking much","shippedFactor":1},
  {"base":"byte","unit":"KB","label":"Kilobyte","factor":1000,"exponent":1,"offset":0},
  {"base":"kg","unit":"kg","label":"Kilograms","factor":1,"exponent":1,"offset":0},
  {"base":"kg/m³","unit":"kg/1000m³","label":"Kilograms per thousand cubic meters","factor":0.001,"exponent":1,"offset":0},
  {"base":"kg/m²","unit":"kg/ha","label":"Kilograms per hectare","factor":0.0001,"exponent":1,"offset":0},
  {"base":"kg/kg","unit":"kg/kg","label":"kilograms per kilogram","factor":1,"exponent":1,"offset":0},
  {"base":"kg/m³","unit":"kg/L","label":"Kilograms per liter","factor":1000,"exponent":1,"offset":0},
  {"base":"kg/m","unit":"kg/m","label":"Kilogram per meter","factor":1,"exponent":1,"offset":0},
  {"base":"kg/m²","unit":"kg/m²","label":"Kilograms per square meter","factor":1,"exponent":1,"offset":0},
  {"base":"kg/m³","unit":"kg/m³","label":"Kilograms per cubic meter","factor":1,"exponent":1,"offset":0},
  {"base":"kPa","unit":"kgf/cm²","label":"Kilograms force per square meter","factor":98.1,"exponent":1,"offset":0},
  {"base":"N","unit":"kips","label":"Thousand pounds force","factor":4448.2216152605,"exponent":1,"offset":0},
  {"base":"J","unit":"kJ","label":"Kilojoule","factor":1000,"exponent":1,"offset":0},
  {"base":"J/W/day","unit":"kJ/W/hr","label":"Kilojoules per watt per hour","factor":24000,"exponent":1,"offset":0},
  {"base":"m","unit":"km","label":"Kilometers","factor":1000,"exponent":1,"offset":0},
  {"base":"m/day","unit":"km/hr","label":"Kilometers per hour","factor":24000,"exponent":1,"offset":0},
  {"base":"N","unit":"kN","label":"Kilonewton","factor":1000,"exponent":1,"offset":0},
  {"base":"m/day","unit":"knots","label":"Nautical miles per hour","factor":44448,"exponent":1,"offset":0},
  {"base":"kPa","unit":"kPa","label":"Kilopascals","factor":1,"exponent":1,"offset":0},
  {"base":"kPa/m","unit":"kPa/m","label":"Kilopascals per meter","factor":1,"exponent":1,"offset":0},
  {"base":"m/day","unit":"kph","label":"Kilometers per hour","factor":24000,"exponent":1,"offset":0},
  {"base":"V","unit":"kV","label":"Kilovolt","factor":1000,"exponent":1,"offset":0},
  {"base":"W","unit":"kW","label":"Kilowatt","factor":1000,"exponent":1,"offset":0},
  {"base":"W/m²","unit":"kW/mm²","label":"Kilowatts per square millimeter","factor":1000000000,"exponent":1,"offset":0},
  {"base":"m³","unit":"L","label":"Liters","factor":0.001,"exponent":1,"offset":0},
  {"base":"m³/kg","unit":"L/100kg","label":"Liters per one hundred kilograms","factor":0.00001,"exponent":1,"offset":0},
  {"base":"m³/m²","unit":"L/ha","label":"Liters per hectare","factor":1e-7,"exponent":1,"offset":0},
  {"base":"m³/m","unit":"L/m","label":"Liters per meter","factor":0.001,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"L/min","label":"Liters per minute","factor":1.44,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"L/s","label":"Liters per second","factor":86.4,"exponent":1,"offset":0},
  {"base":"m³/kg","unit":"L/sack","label":"Liters per 100 pound sack","factor":0.0000220462262184878,"exponent":1,"offset":0},
  {"base":"m³/stk","unit":"L/stk","label":"Liters per stroke","factor":0.001,"exponent":1,"offset":0},
  {"base":"m³/kg","unit":"L/tonne","label":"Liters per tonne mass","factor":0.000001,"exponent":1,"offset":0},
  {"base":"kg","unit":"lb","label":"Pounds (avoirdupois)","factor":0.45359237,"exponent":1,"offset":0},
  {"base":"kg/m³","unit":"lb/1000ft³","label":"Pounds per thousand cubic foot","factor":0.01601846250554,"exponent":1,"offset":0},
  {"base":"kg/m³","unit":"lb/1000gal","label":"Pounds per thousand US gallons","factor":0.1198264284,"exponent":1,"offset":0},
  {"base":"kg/m²","unit":"lb/acre","label":"Pounds per acre","factor":0.000112085993340458,"exponent":1,"offset":0},
  {"base":"kg/m³","unit":"lb/bbl","label":"Pounds per Oil barrel","factor":2.853013476,"exponent":1,"offset":0},
  {"base":"kg/m","unit":"lb/ft","label":"Pound mass per foot","factor":1.48816394356955,"exponent":1,"offset":0},
  {"base":"kg/m²","unit":"lb/ft²","label":"Pounds per square foot","factor":4.88242763638305,"exponent":1,"offset":0},
  {"base":"kg/m³","unit":"lb/ft³","label":"Pounds per cubic foot","factor":16.0184633739601,"exponent":1,"offset":0},
  {"base":"kg/m³","unit":"lb/gal","label":"Pounds per US gallons","factor":119.826428404623,"exponent":1,"offset":0},
  {"base":"kg/day","unit":"lb/hr","label":"Pounds (avoirdupois) per hour","factor":10.88621688,"exponent":1,"offset":0},
  {"base":"kg/kg","unit":"lb/lb","label":"Pounds mass per pounds mass","factor":1,"exponent":1,"offset":0},
  {"base":"kg/J","unit":"lb/MMBTU","label":"Pounds per million British Thermal Units","factor":4.29922642209161e-10,"exponent":1,"offset":0},
  {"base":"kg/m³","unit":"lb/MMCF","label":"Pounds per million cubic feet","factor":0.0000160184633739601,"exponent":1,"offset":0},
  {"base":"N","unit":"lbf","label":"Pounds force","factor":4.4482216152605,"exponent":1,"offset":0},
  {"base":"kPa","unit":"lbf/100ft²","label":"Pounds force per hundred square feet","factor":0.000478802589803,"exponent":1,"offset":0},
  {"base":"N/m","unit":"lbf/in","label":"Pounds force per inch","factor":175.126835246476,"exponent":1,"offset":0},
  {"base":"m","unit":"m","label":"Meter","factor":1,"exponent":1,"offset":0},
  {"base":"m","unit":"m(elv)","label":"Meters - elevation, ie: increasing values going up","factor":-1,"exponent":1,"offset":0},
  {"base":"m/day","unit":"m/day","label":"Meters per day","factor":1,"exponent":1,"offset":0},
  {"base":"m/day","unit":"m/hr","label":"Meters per hour","factor":24,"exponent":1,"offset":0},
  {"base":"m/day","unit":"m/min","label":"Meters per minute","factor":1440,"exponent":1,"offset":0},
  {"base":"m/day","unit":"m/s","label":"Meters per second","factor":86400,"exponent":1,"offset":0},
  {"base":"m²","unit":"m²","label":"Square meters","factor":1,"exponent":1,"offset":0},
  {"base":"m²/day","unit":"m²/day","label":"Square meters per day","factor":1,"exponent":1,"offset":0},
  {"base":"m³","unit":"m³","label":"Cubic meters","factor":1,"exponent":1,"offset":0},
  {"base":"m³/rpm","unit":"m³/100rpm","label":"Cubic meters per 100 rotations per minute","factor":0.01,"exponent":1,"offset":0},
  {"base":"m³/m","unit":"m³/cm","label":"Cubic meter per centimeter","factor":100,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"m³/day","label":"Cubic meters per day","factor":1,"exponent":1,"offset":0},
  {"base":"m³/m³","unit":"m³/E3m³","label":"Cubic meters per thousand cubic meters","factor":0.001,"exponent":1,"offset":0},
  {"base":"m³/m²","unit":"m³/ha","label":"Cubic meters per hectare","factor":0.0001,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"m³/hr","label":"Cubic meters per hour","factor":24,"exponent":1,"offset":0},
  {"base":"m³/m","unit":"m³/m","label":"Cubic meter per meter","factor":1,"exponent":1,"offset":0},
  {"base":"m³/m³","unit":"m³/m³","label":"Cubic meters per cubic meter","factor":1,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"m³/min","label":"Cubic meters per minute","factor":1440,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"m³/s","label":"Cubic meters per second","factor":86400,"exponent":1,"offset":0},
  {"base":"m³/kg","unit":"m³/sack","label":"Cubic meters per 100 pound sack","factor":0.0220462262184878,"exponent":1,"offset":0},
  {"base":"m³/stk","unit":"m³/stk","label":"Cubic meters per stroke","factor":1,"exponent":1,"offset":0},
  {"base":"m³/kg","unit":"m³/tonne","label":"Cubic meters per tonne","factor":0.001,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"m³/yr","label":"Cubic meters per year","factor":0.00273972602,"exponent":1,"offset":0},
  {"base":"byte","unit":"MB","label":"Megabyte","factor":1000000,"exponent":1,"offset":0},
  {"base":"kPa","unit":"mbars","label":"Millibars","factor":0.1,"exponent":1,"offset":0},
  {"base":"m³","unit":"MCF","label":"Thousand cubic feet","factor":28.31685,"exponent":1,"offset":0},
  {"base":"m³/m³","unit":"MCF/bbl","label":"Thousand cubic feet per barrel","factor":178.107606679035,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"MCF/day","label":"Thousand cubic feet per day","factor":28.316846592,"exponent":1,"offset":0},
  {"base":"m²","unit":"mdarcy","label":"Millidarcy","factor":9.869233e-16,"exponent":1,"offset":0},
  {"base":"kg/kg/m³","unit":"meq/L","label":"Milliequivalents per liter","factor":1,"exponent":1,"offset":0},
  {"base":"kg/kg","unit":"mg/kg","label":"milligrams per kilogram","factor":0.000001,"exponent":1,"offset":0},
  {"base":"kg/m³","unit":"mg/L","label":"Milligrams per liter","factor":0.001,"exponent":1,"offset":0},
  {"base":"m","unit":"miles","label":"Miles","factor":1609.344,"exponent":1,"offset":0},
  {"base":"days","unit":"min","label":"Minutes","factor":0.000694444444444444,"exponent":1,"offset":0},
  {"base":"m/day","unit":"min/ft","label":"Minutes per foot","factor":0.00227836103820356,"exponent":-1,"offset":0,"note":"reciprocal: time per distance against distance per time"},
  {"base":"m/day","unit":"min/m","label":"minutes per meter","factor":0.000694444444444444,"exponent":-1,"offset":0,"note":"reciprocal: time per distance against distance per time"},
  {"base":"J","unit":"MJ","label":"Megajoule","factor":1000000,"exponent":1,"offset":0},
  {"base":"J/day","unit":"MJ/day","label":"Megajoule per day","factor":1000,"exponent":1,"offset":0},
  {"base":"J/day","unit":"MJ/hr","label":"Megajoule per hour","factor":24000,"exponent":1,"offset":0},
  {"base":"J/m³","unit":"MJ/m³","label":"Megajoule per cubic meter","factor":1000000,"exponent":1,"offset":0},
  {"base":"m³","unit":"mL","label":"Milliliters","factor":0.000001,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"mL/30min","label":"Milliliters per thirty minutes","factor":0.000048,"exponent":1,"offset":0},
  {"base":"m³/m³","unit":"mL/m³","label":"Milliliter per cubic meter","factor":0.000001,"exponent":1,"offset":0},
  {"base":"m³/m³","unit":"mL/mL","label":"Milliliter per milliliter","factor":1,"exponent":1,"offset":0},
  {"base":"m","unit":"mm","label":"Millimeter","factor":0.001,"exponent":1,"offset":0},
  {"base":"m²","unit":"mm²","label":"Square millimeters","factor":0.000001,"exponent":1,"offset":0},
  {"base":"m²/day","unit":"mm²/s","label":"Square milllimeters per second","factor":0.0864,"exponent":1,"offset":0},
  {"base":"J/day","unit":"MMBTU/day","label":"Million British thermal units per day","factor":947.81624,"exponent":1,"offset":0},
  {"base":"J/day","unit":"MMBTU/hr","label":"Million British thermal units per hour","factor":22747.5898,"exponent":1,"offset":0},
  {"base":"J/m³","unit":"MMBTU/MCF","label":"Million british thermal units/ thousand cubic feet","factor":37258945.8078313,"exponent":1,"offset":0},
  {"base":"m³","unit":"MMCF","label":"Million cubic feet","factor":28316.846592,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"MMCF/day","label":"Million cubic feet per day","factor":28316.846592,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"MMCF/hr","label":"Million cubic feet per hour","factor":679604.318208,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"MMCF/yr","label":"Million cubic feet per year","factor":77.5804016219178,"exponent":1,"offset":0},
  {"base":"kPa","unit":"mmHg","label":"Millimeters of mercury","factor":0.133322368421,"exponent":1,"offset":0},
  {"base":"mol","unit":"mol","label":"Moles","factor":1,"exponent":1,"offset":0},
  {"base":"mol/mol","unit":"mol%","label":"Mole percent","factor":0.01,"exponent":1,"offset":0},
  {"base":"mol/mol","unit":"mol/kmol","label":"Mole per kilomole","factor":0.001,"exponent":1,"offset":0},
  {"base":"kPa","unit":"MPa","label":"Megapascal","factor":1000,"exponent":1,"offset":0},
  {"base":"Pa•s","unit":"mPa•s","label":"Pascal seconds","factor":0.001,"exponent":1,"offset":0},
  {"base":"m/day","unit":"mph","label":"Miles per hour","factor":38624.256,"exponent":1,"offset":0},
  {"base":"S/m","unit":"mS/ft","label":"Millisiemens per foot","factor":0.00328083989501312,"exponent":1,"offset":0},
  {"base":"S/m","unit":"mS/m","label":"Millisiemens per meter","factor":0.001,"exponent":1,"offset":0},
  {"base":"V","unit":"mV","label":"Millivolt","factor":0.001,"exponent":1,"offset":0},
  {"base":"N","unit":"N","label":"Newton","factor":1,"exponent":1,"offset":0},
  {"base":"N/m","unit":"N/m","label":"Newtons per meter","factor":1,"exponent":1,"offset":0},
  {"base":"N•m","unit":"N•m","label":"Newton meters","factor":1,"exponent":1,"offset":0},
  {"base":"m","unit":"NM","label":"Nautical mile","factor":1852,"exponent":1,"offset":0},
  {"base":"V","unit":"nV","label":"Nanovolt","factor":1e-9,"exponent":1,"offset":0},
  {"base":"ohm","unit":"ohm","label":"ohm","factor":1,"exponent":1,"offset":0},
  {"base":"ohm•m","unit":"ohm•m","label":"Ohm meter","factor":1,"exponent":1,"offset":0},
  {"base":"kPa","unit":"Pa","label":"Pascal","factor":0.001,"exponent":1,"offset":0},
  {"base":"Pa•s","unit":"Pa•s","label":"Pascal seconds","factor":1,"exponent":1,"offset":0},
  {"base":"Pa•s^n","unit":"Pa•s^n","label":"Pascal seconds to the n","factor":1,"exponent":1,"offset":0},
  {"base":"Proportion","unit":"ppb","label":"Parts per billion","factor":1e-9,"exponent":1,"offset":0},
  {"base":"Proportion","unit":"ppm","label":"Parts per million","factor":0.000001,"exponent":1,"offset":0},
  {"base":"Proportion","unit":"ppt","label":"Parts per thousand","factor":0.001,"exponent":1,"offset":0},
  {"base":"kPa","unit":"psi","label":"Pounds per square inch","factor":6.894757,"exponent":1,"offset":0},
  {"base":"kPa/m","unit":"psi/ft","label":"Pounds per square inch per foot","factor":22.620593832021,"exponent":1,"offset":0},
  {"base":"rpm","unit":"rpm","label":"Rotations per minute","factor":1,"exponent":1,"offset":0},
  {"base":"days","unit":"s","label":"Seconds","factor":0.000011574074074074,"exponent":1,"offset":0},
  {"base":"days/m³","unit":"s/L","label":"Seconds per liter","factor":0.0115740740740741,"exponent":1,"offset":0},
  {"base":"days/m³","unit":"s/qt","label":"Seconds per U.S. quart","factor":0.0122301876091735,"exponent":1,"offset":0},
  {"base":"kg","unit":"sacks","label":"100 pound sack","factor":45.359237,"exponent":1,"offset":0},
  {"base":"kg/day","unit":"sacks/day","label":"100 pound sacks per day","factor":45.359237,"exponent":1,"offset":0},
  {"base":"kg/m³","unit":"sg(h2o)","label":"Specific gravity to water at 4 degrees C","factor":1000,"exponent":1,"offset":0},
  {"base":"shots/m","unit":"shots/ft","label":"Shots per foot","factor":3.28083989501312,"exponent":1,"offset":0},
  {"base":"shots/m","unit":"shots/m","label":"Shots per meter","factor":1,"exponent":1,"offset":0},
  {"base":"spm","unit":"spm","label":"Strokes per minute","factor":1,"exponent":1,"offset":0},
  {"base":"N","unit":"tonnef","label":"Tonne force","factor":9806.65,"exponent":1,"offset":0},
  {"base":"kg","unit":"tonnes","label":"Tonne mass","factor":1000,"exponent":1,"offset":0},
  {"base":"kg/day","unit":"tonnes/day","label":"Tonne mass per day","factor":1000,"exponent":1,"offset":0},
  {"base":"kg/day","unit":"tonnes/yr","label":"Tonne mass per year","factor":2.73972602739726,"exponent":1,"offset":0},
  {"base":"V","unit":"V","label":"Volt","factor":1,"exponent":1,"offset":0},
  {"base":"m³/m³","unit":"v/v","label":"Volume per volume ratio","factor":1,"exponent":1,"offset":0},
  {"base":"W","unit":"W","label":"Watt","factor":1,"exponent":1,"offset":0},
  {"base":"W/m²","unit":"W/m²","label":"Watts per square meter","factor":1,"exponent":1,"offset":0},
  {"base":"m³/day","unit":"cm³/30min","label":"Cubic centimeters per thirty minutes","factor":0.000048,"exponent":1,"offset":0},
];
